---
- hosts: "{{node}}"
  vars:
    src: /localpath/knight
    dest: /path/knight
  remote_user: root
  tasks:
    - name: ping
      ping:
      tags:
        - ping
    - name: sync code
      tags:
        - sync
      synchronize:
        src: "{{ src }}"
        dest: "{{ dest }}"
        delete: yes
        dest_port: 22
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"
    - name: "build" 
      shell: "cd {{ dest }}; echo fuck world"
      tags: 
        - build
